steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'clone-repositories'
    entrypoint: 'bash'
    env:
      - '_SSH_KEY_SECRET=${_SSH_KEY_SECRET}'
      - '_REPOSITORIES=${_REPOSITORIES}'
    args:
      - '-c'
      - |
        chmod +x ./scripts/clone_repositories.sh
        ./scripts/clone_repositories.sh

  # Terraform drift detection
  - name: 'alpine:latest'
    id: 'drift-detection'
    entrypoint: 'sh'
    env:
      - '_TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
      - '_TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}'
      - '_REPOSITORIES=${_REPOSITORIES}'
    args:
      - '-c'
      - |
        chmod +x ./scripts/drift_detection.sh
        ./scripts/drift_detection.sh

  # Send notifications
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'send-notification'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set -e

        apt-get update && apt-get install -y jq python3-pip && \
        python3 -m pip install jinja2-cli
        
        WEBHOOK_URL=$(gcloud secrets versions access latest --secret=${_CHAT_WEBHOOK_SECRET})
        FAILURE_DETECTED=$(cat /workspace/failure_detected.txt)
        if [ "$$FAILURE_DETECTED" = "true" ]; then
          jinja2 notifications/templates/failure.json.j2 \
            -D build_id="${BUILD_ID}" \
            -D project="${PROJECT_ID}" \
            | curl -sS -X POST -H 'Content-Type: application/json' "$$WEBHOOK_URL" -d @-
          echo "Failure notification sent"
          exit 0
        fi

        DRIFT_DETECTED=$(cat /workspace/drift_detected.txt)
        
        if [ "$$DRIFT_DETECTED" = "true" ]; then
          DRIFT_REPORT=$(cat /workspace/drift_report.json)
          DRIFT_COUNT=$(echo "$$DRIFT_REPORT" | jq 'length')
          DRIFT_DETAILS=$(
            echo "$$DRIFT_REPORT" | jq -r '.[] |
              "• <b>Repo:</b> \(.repository)<br>&nbsp;&nbsp;<b>Path:</b> \(.path)<br>&nbsp;&nbsp;<b>Workspace:</b> \(.workspace)<br>&nbsp;&nbsp;<b>Type:</b> \(.type)<br>"' |
              tr -d '\n'
          )

          jinja2 notifications/templates/drift.json.j2 \
            -D project="${PROJECT_ID}" \
            -D build_id="${BUILD_ID}" \
            -D count="$${DRIFT_COUNT}" \
            -D details="$${DRIFT_DETAILS}" \
            | curl -sS -X POST -H 'Content-Type: application/json' "$$WEBHOOK_URL" -d @-

        else
          jinja2 notifications/templates/success.json.j2 \
            -D build_id="${BUILD_ID}" \
            -D project="${PROJECT_ID}" \
            | curl -sS -X POST -H 'Content-Type: application/json' "$$WEBHOOK_URL" -d @-
        fi

        echo "Notification sent successfully"

substitutions:
  _TERRAFORM_VERSION: '1.5.7'
  _TERRAGRUNT_VERSION: '0.88.1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

timeout: '3600s'